name: flutter_wallet_card_example
description: Demonstrates how to use the flutter_wallet_card plugin.
version: 2.0.0

publish_to: "none"

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_wallet_card:
    path: ../

  cupertino_icons: ^1.0.5
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - passes/example.pkpass
