name: flutter_wallet_card
description: Flutter wallet card for iOS & android devices.
version: 2.0.0
homepage: https://github.com/WebEferen/flutter_wallet_card
repository: https://github.com/WebEferen/flutter_wallet_card.git
issue_tracker: https://github.com/WebEferen/flutter_wallet_card/issues

environment:
  sdk: ">=2.19.1 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  pass_flutter: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # pedantic: ^1.11.0
  # mockito: ^5.0.10
  # build_runner: ^2.0.4

flutter:
  plugin:
    platforms:
      #      android:
      #        package: com.suncern.flutter_wallet_card
      #        pluginClass: FlutterWalletCardPlugin
      ios:
        pluginClass: FlutterWalletCardPlugin
